// src/routes/device-page.vue
<script setup lang="ts">
import type { DeviceLogEntry } from '@/lib/device-serial';
import { useRoute } from 'vue-router';
import { useDevice } from '@/composables/use-device';
import DeviceDiagnostics from '@/components/device-diagnostics.vue';
import DeviceDisplayPicker from '@/components/device-display-picker.vue';
const route = useRoute();
const {
  config,
  connection,
  openNetwork,
  changePassword,
  passwordSet,
  busy,
  networks,
  readingLogs,
  following,
  logs,
  lost,
  diagnosticsCopyStatus,
  status,
  notice,
  error,
  copyStatus,
  logViewport,
  secure,
  supported,
  connected,
  connect,
  disconnect,
  save,
  scanWifi,
  selectNetwork,
  readSettings,
  readLogs,
  readStatus,
  copyDiagnostics,
  copyLogs,
  downloadLogs,
  toggleFollowing,
} = useDevice();
const buttonClass =
  'rounded border border-[var(--panel-border)] px-4 py-2 text-sm transition hover:border-[var(--panel-text)] hover:text-[var(--panel-text)] disabled:cursor-not-allowed disabled:opacity-40';
const primaryClass = `${buttonClass} border-[var(--panel-text)] bg-[var(--panel-text)] text-white hover:bg-[var(--panel-text-soft)] hover:text-white`;

function timestamp(entry: DeviceLogEntry): string {
  if (entry.unix_ms === null) {
    return 'UTC unsynced';
  }
  const date = new Date(entry.unix_ms);
  return Number.isNaN(date.getTime())
    ? `UTC(ms) ${entry.unix_ms}`
    : date.toISOString();
}
</script>
<template>
  <section class="space-y-8">
    <div class="space-y-3">
      <p class="text-[0.7rem] font-semibold text-[var(--muted-text)]">
        USB device
      </p>
      <h1 class="text-3xl font-semibold text-[var(--app-text)]">
        Connect your SLPanel
      </h1>
      <p class="max-w-3xl text-sm leading-7 text-[var(--muted-text)]">
        Plug in the panel with a USB data cable to configure Wi-Fi or read its
        logs. Close any terminal or other app using the device first.
      </p>
    </div>
    <p v-if="!secure" role="alert" class="text-amber-800">
      Open this page over HTTPS or on localhost to connect a USB device.
    </p>
    <p v-else-if="!supported" role="alert" class="text-amber-800">
      This browser does not support Web Serial. Open this page in desktop Chrome
      or Edge.
    </p>
    <div
      class="flex flex-wrap items-center gap-3 rounded-lg border border-[var(--panel-border)] bg-[var(--card-bg)] p-5"
    >
      <span
        :class="`mr-auto text-sm ${connected ? 'text-emerald-800' : 'text-[var(--muted-text)]'}`"
        role="status"
      >
        <template v-if="connection === 'connected'">{{
          'Connected via USB'
        }}</template
        ><template v-else
          ><template v-if="connection === 'connecting'">{{
            'Connecting…'
          }}</template
          ><template v-else>{{
            connection === 'disconnecting'
              ? 'Disconnecting…'
              : 'No device connected'
          }}</template></template
        >
      </span>
      <UButton
        v-if="connected"
        variant="outline"
        type="button"
        :class="buttonClass"
        @click="disconnect"
      >
        Disconnect </UButton
      ><UButton
        v-else
        variant="solid"
        type="button"
        :class="primaryClass"
        :disabled="!secure || !supported || connection !== 'disconnected'"
        @click="connect"
      >
        {{ connection === 'connecting' ? 'Connecting…' : 'Connect device' }}
      </UButton>
    </div>
    <p
      v-if="error"
      role="alert"
      class="rounded-lg border border-rose-400/30 bg-rose-500/10 p-4 text-sm text-rose-800"
    >
      {{ error }}
    </p>
    <p v-if="notice" role="status" class="text-sm text-[var(--panel-text)]">
      {{ notice }}
    </p>
    <div
      class="grid gap-6 lg:grid-cols-[minmax(0,4fr)_minmax(0,6fr)] lg:items-start"
    >
      <form
        class="space-y-5 rounded-lg border border-[var(--panel-border)] bg-[var(--card-bg)] p-5"
        aria-label="USB device configuration"
        @submit.prevent="save"
      >
        <div class="space-y-2">
          <h3 class="text-lg font-semibold text-[var(--app-text)]">
            Device configuration
          </h3>
          <p class="text-sm leading-6 text-[var(--muted-text)]">
            Connect to load saved settings from the device, then edit them. The
            device never exports its Wi-Fi password.
          </p>
        </div>
        <fieldset
          :disabled="!connected || Boolean(busy)"
          class="space-y-4 disabled:opacity-60"
        >
          <div class="space-y-2">
            <UButton
              variant="outline"
              type="button"
              :class="buttonClass"
              @click="scanWifi"
            >
              {{
                busy === 'wifi-scan' ? 'Scanning Wi-Fi…' : 'Scan Wi-Fi networks'
              }}
            </UButton>
            <p class="text-xs text-[var(--muted-text)]" role="status">
              <template v-if="busy === 'wifi-scan'">
                {{
                  'Looking for nearby networks. The panel shows a train while scanning.'
                }} </template
              ><template v-else>
                {{
                  networks?.length === 0
                    ? 'No networks found. Try scanning again or enter a hidden network below.'
                    : 'Scan for nearby 2.4 GHz networks, or enter a hidden network below.'
                }}
              </template>
            </p>
            <div
              v-if="networks && networks.length > 0"
              class="space-y-2"
              aria-label="Available Wi-Fi networks"
            >
              <template
                v-for="network in networks"
                :key="`${network.ssid}-${network.secured}`"
              >
                <UButton
                  variant="outline"
                  type="button"
                  :class="`${buttonClass} flex w-full items-center justify-between gap-3 text-left`"
                  @click="() => selectNetwork(network)"
                >
                  <span>{{ network.ssid }}</span>
                  <span class="text-xs text-[var(--muted-text)]">
                    {{ network.secured ? 'Password required' : 'Open' }} ·{{
                      ' '
                    }}
                    {{ network.rssi }} dBm
                  </span>
                </UButton>
              </template>
            </div>
          </div>
          <div class="space-y-2">
            <label for="device-ssid" class="text-sm"> Wi-Fi name </label>
            <UInput
              id="device-ssid"
              v-model="config.wifi_ssid"
              class="w-full"
              auto-complete="off"
              required
            ></UInput>
          </div>
          <div class="space-y-2">
            <label for="device-security" class="text-sm">
              Wi-Fi security
            </label>
            <USelect
              id="device-security"
              v-model="config.wifi_security"
              :items="[
                { value: 'auto', label: 'Automatic (WPA2/WPA3)' },
                { value: 'wpa2', label: 'WPA2 (compatibility)' },
                { value: 'wpa3', label: 'WPA3 only' },
              ]"
              :disabled="config.wifi_security === undefined || openNetwork"
              class="w-full"
            />
            <p class="text-sm text-[var(--muted-text)]">
              Use WPA2 to test mixed-network compatibility, or WPA3 for a
              WPA3-only network.
            </p>
          </div>
          <div class="space-y-2">
            <label class="flex items-center gap-2 text-sm">
              <input v-model="changePassword" type="checkbox" /> Update Wi-Fi
              password
            </label>
            <label for="device-password" class="text-sm">
              Wi-Fi password
            </label>
            <UInput
              id="device-password"
              v-model="config.wifi_password"
              type="password"
              class="w-full"
              :disabled="!changePassword || openNetwork"
              :required="changePassword && !openNetwork"
              auto-complete="new-password"
            ></UInput>
            <p class="text-xs leading-5 text-[var(--muted-text)]">
              {{
                passwordSet
                  ? 'A Wi-Fi password is saved on the device.'
                  : 'No Wi-Fi password is saved on the device.'
              }}{{ ' ' }} Leave the update option unchecked to keep it
              unchanged.
            </p>
            <label class="flex items-center gap-2 text-sm">
              <input
                v-model="openNetwork"
                type="checkbox"
                :disabled="!changePassword"
              />
              Open Wi-Fi network (no password)
            </label>
          </div>
          <div class="space-y-2">
            <label for="device-origin" class="text-sm"> Service URL </label>
            <UInput
              id="device-origin"
              v-model="config.service_origin"
              type="url"
              class="w-full"
              required
            ></UInput>
          </div>
          <div class="space-y-2">
            <DeviceDisplayPicker
              v-model:display-id="config.display_id"
              :owner-id="
                typeof route.query.owner === 'string' ? route.query.owner : null
              "
              :service-origin="config.service_origin"
            />
            <label for="device-display" class="text-sm"> Display ID </label>
            <UInput
              id="device-display"
              v-model="config.display_id"
              class="w-full"
              required
            ></UInput>
            <p class="text-xs leading-5 text-[var(--muted-text)]">
              Choose a display from the Service URL above, or type an ID
              manually.
            </p>
          </div>
        </fieldset>
        <UButton
          variant="solid"
          type="submit"
          :class="primaryClass"
          :disabled="!connected || Boolean(busy)"
        >
          {{ busy === 'config' ? 'Saving…' : 'Save to device' }}
        </UButton>
        <UButton
          variant="outline"
          type="button"
          :class="buttonClass"
          :disabled="!connected || Boolean(busy)"
          @click="readSettings"
        >
          {{ busy === 'settings' ? 'Loading…' : 'Reload settings' }}
        </UButton>
        <p class="text-xs leading-5 text-[var(--muted-text)]">
          Wi-Fi credentials stay in this page’s memory and are cleared from the
          password field after saving. Reboot the panel after saving.
        </p>
      </form>
      <div
        class="min-w-0 space-y-5 rounded-lg border border-[var(--panel-border)] bg-[var(--card-bg)] p-5"
      >
        <div class="space-y-2">
          <h3 class="text-lg font-semibold text-[var(--app-text)]">
            Device logs
          </h3>
          <p class="text-sm leading-6 text-[var(--muted-text)]">
            Logs stream automatically when connected. UTC timestamps appear once
            the panel has synchronized its clock.
          </p>
        </div>
        <div class="flex flex-wrap gap-2">
          <UButton
            variant="outline"
            type="button"
            :class="buttonClass"
            :disabled="!connected || readingLogs"
            @click="() => void readLogs(false)"
          >
            {{ readingLogs && !following ? 'Reading…' : 'Read logs' }}
          </UButton>
          <UButton
            variant="outline"
            type="button"
            :class="following ? primaryClass : buttonClass"
            :disabled="!connected || (readingLogs && !following)"
            @click="toggleFollowing"
          >
            {{ following ? 'Stop following' : 'Follow logs' }}
          </UButton>
          <UButton
            variant="outline"
            type="button"
            :class="buttonClass"
            :disabled="!logs.length"
            @click="copyLogs"
          >
            Copy logs
          </UButton>
          <UButton
            variant="outline"
            type="button"
            :class="buttonClass"
            :disabled="!logs.length"
            @click="downloadLogs"
          >
            Download logs
          </UButton>
        </div>
        <span role="status" class="text-xs text-[var(--muted-text)]">
          {{ copyStatus }}
        </span>
        <p v-if="lost > 0" role="status" class="text-sm text-amber-800">
          {{ lost }} log entries were overwritten on the device before they
          could be read.
        </p>
        <div
          ref="logViewport"
          class="max-h-[32rem] min-h-48 overflow-auto rounded-lg border border-[var(--panel-border)] bg-slate-50 p-4"
          aria-label="Device logs"
          role="region"
          :tabIndex="0"
        >
          <p v-if="!logs.length" class="text-sm text-[var(--muted-text)]">
            {{
              following
                ? 'Waiting for log entries…'
                : 'Connect a device to stream its logs.'
            }}
          </p>
          <ol v-else class="space-y-3 font-mono text-xs leading-5">
            <li v-for="entry in logs" :key="entry.seq" class="break-words">
              <div
                :class="
                  entry.level === 'warn'
                    ? 'text-amber-800'
                    : 'text-[var(--muted-text)]'
                "
              >
                #{{ entry.seq }} · {{ timestamp(entry) }} · +{{
                  entry.uptime_ms
                }}
                ms · {{ entry.level }}
              </div>
              <div class="whitespace-pre-wrap">{{ entry.message }}</div>
            </li>
          </ol>
        </div>
        <p class="text-xs text-[var(--muted-text)]">
          This page retains up to 1,000 entries. The device’s log history clears
          on reboot.
        </p>
        <details class="space-y-3 border-t border-[var(--panel-border)] pt-4">
          <summary class="cursor-pointer text-sm text-[var(--muted-text)]">
            Current device diagnostics
          </summary>
          <UButton
            variant="outline"
            type="button"
            :class="buttonClass"
            :disabled="!connected || Boolean(busy)"
            @click="readStatus"
          >
            {{ busy === 'status' ? 'Reading…' : 'Read diagnostics' }}
          </UButton>
          <template v-if="status !== null">
            <DeviceDiagnostics :details="status"></DeviceDiagnostics>
            <details
              open
              class="space-y-3 rounded border border-[var(--panel-border)] bg-slate-50 p-4"
            >
              <summary class="cursor-pointer text-sm font-medium">
                Raw diagnostics
              </summary>
              <div class="flex flex-wrap items-center gap-3">
                <UButton
                  variant="outline"
                  type="button"
                  :class="buttonClass"
                  @click="copyDiagnostics"
                >
                  Copy diagnostics
                </UButton>
                <span role="status" class="text-xs text-[var(--muted-text)]">
                  {{ diagnosticsCopyStatus }}
                </span>
              </div>
              <pre class="whitespace-pre-wrap break-words text-xs leading-6">{{
                status
              }}</pre>
            </details>
          </template>
        </details>
      </div>
    </div>
  </section>
</template>

// src/routes/device-page.tsx
import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';

import {
  DeviceSerialClient,
  getDeviceSerialApi,
  validateDeviceConfig,
} from '@/lib/device-serial';
import type {
  DeviceConfig,
  DeviceLogEntry,
  DeviceRequest,
  SavedDeviceConfig,
  WifiSecurity,
  WifiNetwork,
} from '@/lib/device-serial';

const buttonClass =
  'rounded-full border border-[var(--panel-border)] px-4 py-2 text-sm transition hover:border-[var(--panel-text)] hover:text-[var(--panel-text)] disabled:cursor-not-allowed disabled:opacity-40';
const primaryClass = `${buttonClass} border-[var(--panel-text)] bg-[var(--panel-text)] text-black hover:bg-[var(--panel-text-soft)] hover:text-black`;
const inputClass =
  'w-full rounded-xl border border-[var(--panel-border)] bg-black/30 px-4 py-3 text-base md:text-sm';

type Connection = 'disconnected' | 'connecting' | 'connected' | 'disconnecting';

export function DevicePage() {
  const [searchParams] = useSearchParams();
  const [config, setConfig] = useState<DeviceConfig>(() => ({
    wifi_ssid: '',
    wifi_password: '',
    service_origin:
      window.location.protocol === 'https:'
        ? `${window.location.origin}/`
        : 'https://panel.xr.se/',
    display_id: searchParams.get('display') ?? '',
  }));
  const [connection, setConnection] = useState<Connection>('disconnected');
  const [openNetwork, setOpenNetwork] = useState(false);
  const [changePassword, setChangePassword] = useState(false);
  const [passwordSet, setPasswordSet] = useState(false);
  const [busy, setBusy] = useState<
    'config' | 'settings' | 'logs' | 'status' | 'wifi-scan' | null
  >(null);
  const [networks, setNetworks] = useState<WifiNetwork[] | null>(null);
  const [following, setFollowing] = useState(false);
  const [logs, setLogs] = useState<DeviceLogEntry[]>([]);
  const [lost, setLost] = useState(0);
  const [status, setStatus] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const client = useRef<DeviceSerialClient | null>(null);
  const mounted = useRef(true);
  const generation = useRef(0);
  const follow = useRef(false);
  const cursor = useRef(0);
  const savedSsid = useRef('');
  const logEnd = useRef<HTMLDivElement | null>(null);
  const secure = window.isSecureContext;
  const supported = Boolean(getDeviceSerialApi());
  const connected = connection === 'connected';

  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
      generation.current += 1;
      follow.current = false;
      const current = client.current;
      client.current = null;
      void current?.disconnect();
    };
  }, []);

  useEffect(() => {
    if (following) {
      logEnd.current?.scrollIntoView?.({ block: 'nearest' });
    }
  }, [following, logs]);

  async function connect() {
    const api = getDeviceSerialApi();
    if (!api || !secure) {
      return;
    }
    const attempt = ++generation.current;
    let connecting: DeviceSerialClient | null = null;
    setNetworks(null);
    setConnection('connecting');
    setError(null);
    setNotice(null);
    try {
      // Invoke the picker directly from the click, preserving user activation.
      const port = await api.requestPort({
        filters: [{ usbVendorId: 0xc0de, usbProductId: 0xcafe }],
      });
      if (!mounted.current || generation.current !== attempt) {
        return;
      }
      const next = new DeviceSerialClient(port, (failure) => {
        if (!mounted.current || generation.current !== attempt) {
          return;
        }
        follow.current = false;
        setFollowing(false);
        setConnection('disconnected');
        setBusy(null);
        setError(failure.message);
        client.current = null;
      });
      connecting = next;
      client.current = next;
      await next.connect();
      const saved = await next.request({ op: 'config' });
      if (saved.reply !== 'config') {
        throw new Error(
          'Could not read device settings. Update the firmware and reconnect.',
        );
      }
      if (!mounted.current || generation.current !== attempt) {
        await next.disconnect();
        return;
      }
      cursor.current = 0;
      setLogs([]);
      setLost(0);
      setStatus(null);
      applySavedConfig(saved.config, true);
      setConnection('connected');
      setNotice('Device connected. Saved settings loaded.');
    } catch (failure) {
      await connecting?.disconnect();
      if (!mounted.current || generation.current !== attempt) {
        return;
      }
      client.current = null;
      setConnection('disconnected');
      if (failure instanceof DOMException && failure.name === 'NotFoundError') {
        return;
      }
      setError(
        failure instanceof Error
          ? failure.message
          : 'Could not connect. Close other apps using the USB port and try again.',
      );
    }
  }

  async function disconnect() {
    generation.current += 1;
    follow.current = false;
    setFollowing(false);
    const current = client.current;
    client.current = null;
    setConnection('disconnecting');
    await current?.disconnect();
    if (mounted.current) {
      setConnection('disconnected');
      setBusy(null);
      setNotice('Device disconnected.');
    }
  }

  async function request(request: DeviceRequest, current: DeviceSerialClient) {
    const reply = await current.request(request);
    if (reply.reply === 'error') {
      throw new Error(reply.message);
    }
    return reply;
  }

  async function save(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const current = client.current;
    if (!current || busy) {
      return;
    }
    const attempt = generation.current;
    setError(null);
    setNotice(null);
    try {
      if (changePassword && !openNetwork && !config.wifi_password) {
        throw new Error(
          'Enter a Wi-Fi password, or select an open Wi-Fi network.',
        );
      }
      const update: DeviceConfig = {
        wifi_ssid: config.wifi_ssid,
        wifi_security: config.wifi_security,
        service_origin: config.service_origin,
        display_id: config.display_id,
        ...(changePassword
          ? { wifi_password: openNetwork ? '' : config.wifi_password }
          : {}),
      };
      validateDeviceConfig(update);
      setBusy('config');
      const reply = await request({ op: 'configure', config: update }, current);
      if (!mounted.current || generation.current !== attempt) {
        return;
      }
      if (reply.reply === 'saved') {
        savedSsid.current = update.wifi_ssid;
        if (changePassword) {
          setPasswordSet(!openNetwork);
        }
        setChangePassword(false);
        setOpenNetwork(false);
        setConfig((draft) => ({ ...draft, wifi_password: '' }));
        setNotice(
          reply.reboot_required
            ? 'Configuration saved. Reboot the device to apply it.'
            : 'Configuration saved.',
        );
      }
    } catch (failure) {
      if (mounted.current && generation.current === attempt) {
        setError(readError(failure));
      }
    } finally {
      if (mounted.current && generation.current === attempt) {
        setBusy(null);
      }
    }
  }

  function applySavedConfig(
    saved: SavedDeviceConfig,
    useSelectedDisplay = false,
  ) {
    savedSsid.current = saved.wifi_ssid;
    setConfig({
      wifi_ssid: saved.wifi_ssid,
      wifi_security: saved.wifi_security,
      wifi_password: '',
      service_origin: saved.service_origin,
      display_id: useSelectedDisplay
        ? (searchParams.get('display') ?? saved.display_id)
        : saved.display_id,
    });
    setPasswordSet(saved.wifi_password_set);
    setChangePassword(false);
    setOpenNetwork(false);
  }

  async function readSettings() {
    const current = client.current;
    if (!current || busy) {
      return;
    }
    const attempt = generation.current;
    setBusy('settings');
    setError(null);
    setNotice(null);
    try {
      const reply = await request({ op: 'config' }, current);
      if (!mounted.current || generation.current !== attempt) {
        return;
      }
      if (reply.reply === 'config') {
        applySavedConfig(reply.config);
        setNotice('Saved settings loaded from the device.');
      }
    } catch (failure) {
      if (mounted.current && generation.current === attempt) {
        setError(readError(failure));
      }
    } finally {
      if (mounted.current && generation.current === attempt) {
        setBusy(null);
      }
    }
  }

  async function readLogs(keepFollowing: boolean) {
    const current = client.current;
    if (!current || busy) {
      return;
    }
    const attempt = generation.current;
    follow.current = keepFollowing;
    setFollowing(keepFollowing);
    setBusy('logs');
    setError(null);
    try {
      do {
        const reply = await request(
          { op: 'logs', after: cursor.current },
          current,
        );
        if (!mounted.current || generation.current !== attempt) {
          return;
        }
        if (reply.reply !== 'logs') {
          throw new Error('Unexpected logs response.');
        }
        cursor.current = reply.next;
        setLogs((retained) => [...retained, ...reply.entries].slice(-1000));
        setLost((count) => count + reply.lost);
        // Finish paging on a single read. Stop following after any in-flight page.
        if (keepFollowing && !follow.current) {
          break;
        }
        if (reply.more) {
          continue;
        }
        if (!follow.current) {
          break;
        }
        await new Promise((resolve) => setTimeout(resolve, 250));
      } while (!keepFollowing || follow.current);
    } catch (failure) {
      if (mounted.current && generation.current === attempt) {
        setError(readError(failure));
      }
    } finally {
      if (mounted.current && generation.current === attempt) {
        follow.current = false;
        setFollowing(false);
        setBusy(null);
      }
    }
  }

  async function scanWifi() {
    const current = client.current;
    if (!current || busy) return;
    const attempt = generation.current;
    setBusy('wifi-scan');
    setNetworks(null);
    setError(null);
    setNotice(null);
    try {
      const reply = await request({ op: 'wifi-scan' }, current);
      if (
        mounted.current &&
        generation.current === attempt &&
        reply.reply === 'wifi-scan'
      ) {
        setNetworks(reply.networks);
      }
    } catch (failure) {
      if (mounted.current && generation.current === attempt)
        setError(readError(failure));
    } finally {
      if (mounted.current && generation.current === attempt) setBusy(null);
    }
  }

  function selectNetwork(network: WifiNetwork) {
    // A draft SSID may differ from the network owning the durable password.
    const changed = network.ssid !== savedSsid.current;
    setConfig((draft) => ({
      ...draft,
      wifi_ssid: network.ssid,
      wifi_password: '',
      wifi_security: draft.wifi_security === undefined ? undefined : 'auto',
    }));
    setChangePassword(changed || !network.secured || !passwordSet);
    setOpenNetwork(!network.secured);
  }

  async function readStatus() {
    const current = client.current;
    if (!current || busy) {
      return;
    }
    const attempt = generation.current;
    setBusy('status');
    setError(null);
    try {
      const reply = await request({ op: 'status' }, current);
      if (
        mounted.current &&
        generation.current === attempt &&
        reply.reply === 'status'
      ) {
        setStatus(reply.details);
      }
    } catch (failure) {
      if (mounted.current && generation.current === attempt) {
        setError(readError(failure));
      }
    } finally {
      if (mounted.current && generation.current === attempt) {
        setBusy(null);
      }
    }
  }

  function downloadLogs() {
    const url = URL.createObjectURL(
      new Blob([logs.map((entry) => JSON.stringify(entry)).join('\n') + '\n'], {
        type: 'application/x-ndjson',
      }),
    );
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'slpanel-logs.jsonl';
    anchor.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  return (
    <section className="space-y-8">
      <div className="space-y-3">
        <p className="text-[0.7rem] uppercase tracking-[0.22em] text-[var(--muted-text)]">
          USB device
        </p>
        <h2 className="text-3xl font-semibold text-[var(--panel-text)]">
          Connect your SLPanel
        </h2>
        <p className="max-w-3xl text-sm leading-7 text-[var(--muted-text)]">
          Plug in the panel with a USB data cable to configure Wi-Fi or read its
          logs. Close any terminal or other app using the device first.
        </p>
      </div>

      {!secure ? (
        <p role="alert" className="text-amber-200">
          Open this page over HTTPS or on localhost to connect a USB device.
        </p>
      ) : !supported ? (
        <p role="alert" className="text-amber-200">
          This browser does not support Web Serial. Open this page in desktop
          Chrome or Edge.
        </p>
      ) : null}

      <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-[var(--panel-border)] bg-black/15 p-5">
        <span
          className={`mr-auto text-sm ${connected ? 'text-emerald-300' : 'text-[var(--muted-text)]'}`}
          role="status"
        >
          {connection === 'connected'
            ? 'Connected via USB'
            : connection === 'connecting'
              ? 'Connecting…'
              : connection === 'disconnecting'
                ? 'Disconnecting…'
                : 'No device connected'}
        </span>
        {connected ? (
          <button
            type="button"
            className={buttonClass}
            onClick={() => void disconnect()}
          >
            Disconnect
          </button>
        ) : (
          <button
            type="button"
            className={primaryClass}
            disabled={!secure || !supported || connection !== 'disconnected'}
            onClick={() => void connect()}
          >
            {connection === 'connecting' ? 'Connecting…' : 'Connect device'}
          </button>
        )}
      </div>

      {error ? (
        <p
          role="alert"
          className="rounded-xl border border-rose-400/30 bg-rose-500/10 p-4 text-sm text-rose-100"
        >
          {error}
        </p>
      ) : null}
      {notice ? (
        <p role="status" className="text-sm text-[var(--panel-text-soft)]">
          {notice}
        </p>
      ) : null}

      <div className="grid gap-6 lg:grid-cols-[minmax(0,4fr)_minmax(0,6fr)] lg:items-start">
        <form
          onSubmit={(event) => void save(event)}
          className="space-y-5 rounded-2xl border border-[var(--panel-border)] bg-black/15 p-5"
          aria-label="USB device configuration"
        >
          <div className="space-y-2">
            <h3 className="text-lg font-semibold text-[var(--panel-text)]">
              Device configuration
            </h3>
            <p className="text-sm leading-6 text-[var(--muted-text)]">
              Connect to load saved settings from the device, then edit them.
              The device never exports its Wi-Fi password.
            </p>
          </div>
          <fieldset
            disabled={!connected || Boolean(busy)}
            className="space-y-4 disabled:opacity-60"
          >
            <div className="space-y-2">
              <button
                type="button"
                className={buttonClass}
                onClick={() => void scanWifi()}
              >
                {busy === 'wifi-scan'
                  ? 'Scanning Wi-Fi…'
                  : 'Scan Wi-Fi networks'}
              </button>
              <p className="text-xs text-[var(--muted-text)]" role="status">
                {busy === 'wifi-scan'
                  ? 'Looking for nearby networks. The panel shows a train while scanning.'
                  : networks?.length === 0
                    ? 'No networks found. Try scanning again or enter a hidden network below.'
                    : 'Scan for nearby 2.4 GHz networks, or enter a hidden network below.'}
              </p>
              {networks && networks.length > 0 && (
                <div
                  className="space-y-2"
                  aria-label="Available Wi-Fi networks"
                >
                  {networks.map((network) => (
                    <button
                      key={`${network.ssid}-${network.secured}`}
                      type="button"
                      className={`${buttonClass} flex w-full items-center justify-between gap-3 text-left`}
                      onClick={() => selectNetwork(network)}
                    >
                      <span>{network.ssid}</span>
                      <span className="text-xs text-[var(--muted-text)]">
                        {network.secured ? 'Password required' : 'Open'} ·{' '}
                        {network.rssi} dBm
                      </span>
                    </button>
                  ))}
                </div>
              )}
            </div>
            <div className="space-y-2">
              <label htmlFor="device-ssid" className="text-sm">
                Wi-Fi name
              </label>
              <input
                id="device-ssid"
                className={inputClass}
                value={config.wifi_ssid}
                autoComplete="off"
                onChange={(event) =>
                  setConfig((draft) => ({
                    ...draft,
                    wifi_ssid: event.target.value,
                  }))
                }
                required
              />
            </div>
            <div className="space-y-2">
              <label htmlFor="device-security" className="text-sm">
                Wi-Fi security
              </label>
              <select
                id="device-security"
                className={inputClass}
                value={config.wifi_security ?? 'auto'}
                disabled={config.wifi_security === undefined || openNetwork}
                onChange={(event) =>
                  setConfig((draft) => ({
                    ...draft,
                    wifi_security: event.target.value as WifiSecurity,
                  }))
                }
              >
                <option value="auto">Automatic (WPA2/WPA3)</option>
                <option value="wpa2">WPA2 (compatibility)</option>
                <option value="wpa3">WPA3 only</option>
              </select>
              <p className="text-sm text-[var(--muted-text)]">
                Use WPA2 to test mixed-network compatibility, or WPA3 for a
                WPA3-only network.
              </p>
            </div>
            <div className="space-y-2">
              <label className="flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={changePassword}
                  onChange={(event) => {
                    setChangePassword(event.target.checked);
                    setOpenNetwork(false);
                    if (!event.target.checked) {
                      setConfig((draft) => ({ ...draft, wifi_password: '' }));
                    }
                  }}
                />
                Update Wi-Fi password
              </label>
              <label htmlFor="device-password" className="text-sm">
                Wi-Fi password
              </label>
              <input
                id="device-password"
                type="password"
                className={inputClass}
                value={config.wifi_password ?? ''}
                disabled={!changePassword || openNetwork}
                required={changePassword && !openNetwork}
                autoComplete="new-password"
                onChange={(event) =>
                  setConfig((draft) => ({
                    ...draft,
                    wifi_password: event.target.value,
                  }))
                }
              />
              <p className="text-xs leading-5 text-[var(--muted-text)]">
                {passwordSet
                  ? 'A Wi-Fi password is saved on the device.'
                  : 'No Wi-Fi password is saved on the device.'}{' '}
                Leave the update option unchecked to keep it unchanged.
              </p>
              <label className="flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={openNetwork}
                  disabled={!changePassword}
                  onChange={(event) => {
                    setOpenNetwork(event.target.checked);
                    if (event.target.checked) {
                      setConfig((draft) => ({
                        ...draft,
                        wifi_password: '',
                        wifi_security:
                          draft.wifi_security === undefined
                            ? undefined
                            : 'auto',
                      }));
                    }
                  }}
                />
                Open Wi-Fi network (no password)
              </label>
            </div>
            <div className="space-y-2">
              <label htmlFor="device-origin" className="text-sm">
                Service URL
              </label>
              <input
                id="device-origin"
                type="url"
                className={inputClass}
                value={config.service_origin}
                onChange={(event) =>
                  setConfig((draft) => ({
                    ...draft,
                    service_origin: event.target.value,
                  }))
                }
                required
              />
            </div>
            <div className="space-y-2">
              <label htmlFor="device-display" className="text-sm">
                Display ID
              </label>
              <input
                id="device-display"
                className={inputClass}
                value={config.display_id}
                onChange={(event) =>
                  setConfig((draft) => ({
                    ...draft,
                    display_id: event.target.value,
                  }))
                }
                required
              />
              <p className="text-xs leading-5 text-[var(--muted-text)]">
                Choose a saved display from{' '}
                <Link className="underline" to="/config">
                  Config
                </Link>{' '}
                to use its ID here.
              </p>
            </div>
          </fieldset>
          <button
            type="submit"
            className={primaryClass}
            disabled={!connected || Boolean(busy)}
          >
            {busy === 'config' ? 'Saving…' : 'Save to device'}
          </button>
          <button
            type="button"
            className={buttonClass}
            disabled={!connected || Boolean(busy)}
            onClick={() => void readSettings()}
          >
            {busy === 'settings' ? 'Loading…' : 'Reload settings'}
          </button>
          <p className="text-xs leading-5 text-[var(--muted-text)]">
            Wi-Fi credentials stay in this page’s memory and are cleared from
            the password field after saving. Reboot the panel after saving.
          </p>
        </form>

        <div className="min-w-0 space-y-5 rounded-2xl border border-[var(--panel-border)] bg-black/15 p-5">
          <div className="space-y-2">
            <h3 className="text-lg font-semibold text-[var(--panel-text)]">
              Device logs
            </h3>
            <p className="text-sm leading-6 text-[var(--muted-text)]">
              Read the panel’s last 100 log statements, or follow new entries as
              they arrive. UTC timestamps appear once the panel has synchronized
              its clock.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              className={buttonClass}
              disabled={!connected || Boolean(busy)}
              onClick={() => void readLogs(false)}
            >
              {busy === 'logs' && !following ? 'Reading…' : 'Read logs'}
            </button>
            <button
              type="button"
              className={following ? primaryClass : buttonClass}
              disabled={!connected || (Boolean(busy) && !following)}
              onClick={() => {
                if (following) {
                  follow.current = false;
                  setFollowing(false);
                } else {
                  void readLogs(true);
                }
              }}
            >
              {following ? 'Stop following' : 'Follow logs'}
            </button>
            <button
              type="button"
              className={buttonClass}
              disabled={!logs.length}
              onClick={downloadLogs}
            >
              Download logs
            </button>
          </div>
          {lost > 0 ? (
            <p role="status" className="text-sm text-amber-200">
              {lost} log entries were overwritten on the device before they
              could be read.
            </p>
          ) : null}
          <div
            className="max-h-[32rem] min-h-48 overflow-auto rounded-xl border border-[var(--panel-border)] bg-black/40 p-4"
            aria-label="Device logs"
            role="region"
            tabIndex={0}
          >
            {!logs.length ? (
              <p className="text-sm text-[var(--muted-text)]">
                {busy === 'logs'
                  ? 'Waiting for log entries…'
                  : 'Connect a device and read its logs.'}
              </p>
            ) : (
              <ol className="space-y-3 font-mono text-xs leading-5">
                {logs.map((entry) => (
                  <li key={entry.seq} className="break-words">
                    <div
                      className={
                        entry.level === 'warn'
                          ? 'text-amber-200'
                          : 'text-[var(--muted-text)]'
                      }
                    >
                      #{entry.seq} · {timestamp(entry)} · +{entry.uptime_ms} ms
                      · {entry.level}
                    </div>
                    <div className="whitespace-pre-wrap">{entry.message}</div>
                  </li>
                ))}
              </ol>
            )}
            <div ref={logEnd} />
          </div>
          <p className="text-xs text-[var(--muted-text)]">
            This page retains up to 1,000 entries. The device’s log history
            clears on reboot.
          </p>
          <details className="space-y-3 border-t border-[var(--panel-border)] pt-4">
            <summary className="cursor-pointer text-sm text-[var(--muted-text)]">
              Current device diagnostics
            </summary>
            <button
              type="button"
              className={buttonClass}
              disabled={!connected || Boolean(busy)}
              onClick={() => void readStatus()}
            >
              {busy === 'status' ? 'Reading…' : 'Read diagnostics'}
            </button>
            {status ? (
              <pre className="whitespace-pre-wrap break-words text-xs leading-6">
                {status}
              </pre>
            ) : null}
          </details>
        </div>
      </div>
    </section>
  );
}

function readError(error: unknown): string {
  return error instanceof Error ? error.message : 'Device operation failed.';
}
function timestamp(entry: DeviceLogEntry): string {
  if (entry.unix_ms === null) {
    return 'UTC unsynced';
  }
  const date = new Date(entry.unix_ms);
  return Number.isNaN(date.getTime())
    ? `UTC(ms) ${entry.unix_ms}`
    : date.toISOString();
}
