// src/components/device-display-picker.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { DisplayRecord } from '@/api/types';
import { listDisplays } from '@/lib/config-api';
const displayId = defineModel<string>('displayId', { required: true });
const props = defineProps<{ ownerId: string | null; serviceOrigin: string }>();
const ownerInput = ref(
  props.ownerId ?? window.localStorage.getItem('slpanel.owner-id'),
);
const owner = computed({
  get: () => ownerInput.value ?? displayId.value.split('-')[0],
  set: (value) => {
    ownerInput.value = value.trim();
  },
});
const validOwner = computed(() => /^[A-Za-z0-9]{8}$/.test(owner.value));
const service = computed(() => props.serviceOrigin.trim().replace(/\/+$/, ''));
const validService = computed(() => {
  try {
    const url = new URL(service.value);
    return (
      url.protocol === 'https:' &&
      !url.username &&
      !url.password &&
      !url.search &&
      !url.hash
    );
  } catch {
    return false;
  }
});
const result = ref<{
  owner: string;
  service: string;
  displays: DisplayRecord[];
  error?: string;
} | null>(null);
const current = computed(() =>
  result.value?.owner === owner.value && result.value.service === service.value
    ? result.value
    : null,
);
const items = computed(
  () =>
    current.value?.displays.map((display) => ({
      value: display.id,
      label:
        display.name + (display.site_name ? ` — ${display.site_name}` : ''),
    })) ?? [],
);
const selected = computed({
  get: () =>
    items.value.some((item) => item.value === displayId.value)
      ? displayId.value
      : undefined,
  set: (value) => {
    if (value) displayId.value = value;
  },
});
const placeholder = computed(() =>
  !validOwner.value
    ? 'Enter an 8-character owner ID'
    : !validService.value
      ? 'Enter a valid HTTPS Service URL'
      : !current.value
        ? 'Loading displays…'
        : 'Choose a display',
);
watch(
  () => [owner.value, service.value],
  (_value, _previous, onCleanup) => {
    if (!validOwner.value || !validService.value) return;
    const controller = new AbortController();
    onCleanup(() => controller.abort());
    const requestedOwner = owner.value;
    const requestedService = service.value;
    listDisplays(requestedOwner, controller.signal, requestedService)
      .then((displays) => {
        if (!controller.signal.aborted)
          result.value = {
            owner: requestedOwner,
            service: requestedService,
            displays,
          };
      })
      .catch(() => {
        if (!controller.signal.aborted)
          result.value = {
            owner: requestedOwner,
            service: requestedService,
            displays: [],
            error:
              'Could not load displays. You can still enter a Display ID below.',
          };
      });
  },
  { immediate: true },
);
</script>
<template>
  <div class="space-y-2">
    <UFormField label="Owner ID" name="device-display-owner">
      <UInput
        id="device-display-owner"
        v-model="owner"
        placeholder="Your 8-character owner ID"
        class="w-full"
      />
    </UFormField>
    <UFormField label="Saved display" name="device-saved-display">
      <USelect
        id="device-saved-display"
        v-model="selected"
        :items="items"
        :placeholder="placeholder"
        :disabled="!items.length"
        class="w-full"
      />
    </UFormField>
    <p
      v-if="current?.error"
      role="status"
      class="text-xs leading-5 text-[var(--muted-text)]"
    >
      {{ current.error }}
    </p>
    <p
      v-else-if="current && !current.displays.length"
      class="text-xs leading-5 text-[var(--muted-text)]"
    >
      No saved displays for this owner at the Service URL. Enter an ID below or
      create a display on that service.
    </p>
  </div>
</template>

// src/components/device-display-picker.tsx
import { startTransition, useEffect, useState } from 'react';

import type { DisplayRecord } from '@/api/types';
import { listDisplays } from '@/lib/config-api';

const ownerPattern = /^[A-Za-z0-9]{8}$/;
const inputClass =
  'w-full rounded-xl border border-[var(--panel-border)] bg-black/30 px-4 py-3 text-base md:text-sm';

export function DeviceDisplayPicker({
  displayId,
  ownerId,
  serviceOrigin,
  onSelect,
}: {
  displayId: string;
  ownerId: string | null;
  serviceOrigin: string;
  onSelect: (id: string) => void;
}) {
  const [ownerInput, setOwnerInput] = useState<string | null>(
    ownerId ?? window.localStorage.getItem('slpanel.owner-id'),
  );
  const owner = ownerInput ?? displayId.split('-')[0];
  const [result, setResult] = useState<{
    owner: string;
    service: string;
    displays: DisplayRecord[];
    error?: string;
  } | null>(null);
  const validOwner = ownerPattern.test(owner);
  const service = serviceOrigin.trim().replace(/\/+$/, '');
  let validService = false;
  try {
    const url = new URL(service);
    validService =
      url.protocol === 'https:' &&
      !url.username &&
      !url.password &&
      !url.search &&
      !url.hash;
  } catch {
    // Wait for a complete Service URL before looking up displays.
  }
  const current =
    result?.owner === owner && result.service === service ? result : null;
  const selected = current?.displays.some(
    (display) => display.id === displayId,
  );

  useEffect(() => {
    if (!validOwner || !validService) return;
    const controller = new AbortController();
    listDisplays(owner, controller.signal, service)
      .then((displays) => {
        if (!controller.signal.aborted) {
          startTransition(() => setResult({ owner, service, displays }));
        }
      })
      .catch(() => {
        if (!controller.signal.aborted) {
          setResult({
            owner,
            service,
            displays: [],
            error:
              'Could not load displays. You can still enter a Display ID below.',
          });
        }
      });
    return () => controller.abort();
  }, [owner, validOwner, service, validService]);

  return (
    <div className="space-y-2">
      <label htmlFor="device-display-owner" className="text-sm">
        Owner ID
      </label>
      <input
        id="device-display-owner"
        className={inputClass}
        value={owner}
        onChange={(event) => setOwnerInput(event.target.value.trim())}
        placeholder="Your 8-character owner ID"
      />
      <label htmlFor="device-saved-display" className="block text-sm">
        Saved display
      </label>
      <select
        id="device-saved-display"
        className={inputClass}
        value={selected ? displayId : ''}
        disabled={!current?.displays.length}
        onChange={(event) => {
          if (event.target.value) onSelect(event.target.value);
        }}
      >
        <option value="">
          {!validOwner
            ? 'Enter an 8-character owner ID'
            : !validService
              ? 'Enter a valid HTTPS Service URL'
              : !current
                ? 'Loading displays…'
                : 'Choose a display'}
        </option>
        {current?.displays.map((display) => (
          <option key={display.id} value={display.id}>
            {display.name}
            {display.site_name ? ` — ${display.site_name}` : ''}
          </option>
        ))}
      </select>
      {current?.error ? (
        <p role="status" className="text-xs leading-5 text-[var(--muted-text)]">
          {current.error}
        </p>
      ) : current && current.displays.length === 0 ? (
        <p className="text-xs leading-5 text-[var(--muted-text)]">
          No saved displays for this owner at the Service URL. Enter an ID below
          or create a display on that service.
        </p>
      ) : null}
    </div>
  );
}
